import type{ApiResult,BackgroundTaskRequest,CommandMap,CommandName,CommandPromise,Json,LearningConversionRequest,LearningProgressRequest,ResumeTemplateId}from"./contracts";import type{CommandTransport}from"./transport";import{tauriTransport}from"./transport";
export class CareerCraftClient{constructor(private readonly transport:CommandTransport=tauriTransport){}deleteLearningPath(pathId:string,expectedVersion:number){return this.command("delete_learning_path",{pathId,expectedVersion})}command<K extends CommandName>(name:K,request:CommandMap[K]["request"]|Record<string,unknown>):Promise<CommandMap[K]["response"]>{return this.transport.call(name,request as CommandMap[K]["request"])}
getExperiences(){return this.command("get_experiences",undefined)}saveExperience(payload:Record<string,unknown>){return this.command("save_experience",payload)}deleteExperience(experienceId:string,version:number){return this.command("delete_experience",{experienceId,version})}getPersonas(){return this.command("get_personas",undefined)}createPersona(payload:Record<string,unknown>){return this.command("create_persona",payload)}updatePersona(personaId:string,data:Record<string,unknown>){return this.command("update_persona",{personaId,data})}deletePersona(personaId:string){return this.command("delete_persona",{personaId})}getFitScores(personaId:string){return this.command("get_experiences_with_fit_score",{personaId})}updateFitScore(personaId:string,experienceId:string,score:number){return this.command("update_fit_score",{personaId,experienceId,score})}parseJD(jdText:string){return this.command("parse_jd",{jdText})}matchJob(jobDescId:string,personaId:string){return this.command("match_job",{jobDescId,personaId})}listJobs(){return this.command("list_jobs",undefined)}deleteJob(jobDescId:string){return this.command("delete_job",{jobDescId})}getJobMatches(jobDescId:string){return this.command("get_job_matches",{jobDescId})}updateMatchStatus(matchId:string,status:string){return this.command("update_match_status",{matchId,status})}reframeResume(matchId:string){return this.command("reframe_resume",{matchId})}getReframeResults(matchId:string){return this.command("get_reframe_results",{matchId})}updateReframe(reframeId:string,reframedSummary:string){return this.command("update_reframe",{reframeId,reframedSummary})}resetReframe(reframeId:string){return this.command("reset_reframe",{reframeId})}generateResume(personaId:string,template:ResumeTemplateId){return this.command("generate_resume",{personaId,template})}previewResume(personaId:string,template:ResumeTemplateId){return this.command("preview_resume",{personaId,template})}getLearningPath(skill:string){return this.command("get_learning_path",{skill})}getLearningPaths(){return this.command("get_learning_paths_by_source",undefined)}getSkillGraph(){return this.command("get_skill_graph",undefined)}searchSkills(query:string){return this.command("search_skills",{query})}getSettings(){return this.command("get_settings",undefined)}saveSettings(payload:Record<string,unknown>){return this.command("save_settings",payload)}testLLMConnection(name?:string){return this.command("test_llm_connection",name?{name}:undefined)}}
export interface CareerCraftClient{resetFitScore(personaId:string,experienceId:string):CommandPromise<"reset_fit_score">;deleteProvider(name:string):CommandPromise<"delete_provider">;listCustomSkills():CommandPromise<"list_custom_skills">;createCustomSkill(skill:Record<string,unknown>):CommandPromise<"create_custom_skill">;updateCustomSkill(skill:Record<string,unknown>):CommandPromise<"update_custom_skill">;deleteCustomSkill(skillId:string):CommandPromise<"delete_custom_skill">;simulateSkillWhatIf(payload:Record<string,unknown>):CommandPromise<"simulate_skill_what_if">;updateLearningProgress(payload:LearningProgressRequest):CommandPromise<"update_learning_progress">;completeLearningToExperience(payload:LearningConversionRequest):CommandPromise<"complete_learning_to_experience">;openExternalUrl(token:string):CommandPromise<"open_external_url">;getSkillResources(skillId:string):CommandPromise<"get_skill_resources">}
Object.assign(CareerCraftClient.prototype,{resetFitScore(this:CareerCraftClient,personaId:string,experienceId:string){return this.command("reset_fit_score",{personaId,experienceId})},deleteProvider(this:CareerCraftClient,name:string){return this.command("delete_provider",{name})},listCustomSkills(this:CareerCraftClient){return this.command("list_custom_skills",undefined)},createCustomSkill(this:CareerCraftClient,skill:Record<string,unknown>){return this.command("create_custom_skill",skill)},updateCustomSkill(this:CareerCraftClient,skill:Record<string,unknown>){return this.command("update_custom_skill",skill)},deleteCustomSkill(this:CareerCraftClient,skillId:string){return this.command("delete_custom_skill",{skillId,ownerId:"default"})},simulateSkillWhatIf(this:CareerCraftClient,payload:Record<string,unknown>){return this.command("simulate_skill_what_if",payload)},updateLearningProgress(this:CareerCraftClient,payload:Record<string,unknown>){return this.command("update_learning_progress",payload)},completeLearningToExperience(this:CareerCraftClient,payload:Record<string,unknown>){return this.command("complete_learning_to_experience",payload)},openExternalUrl(this:CareerCraftClient,token:string){return this.command("open_external_url",{token})},getSkillResources(this:CareerCraftClient,skillId:string){return this.command("get_skill_resources",{skillId})}});
const getBuiltinSkills=CareerCraftClient.prototype.getSkillGraph;CareerCraftClient.prototype.getSkillGraph=async function(){const[built,custom]=await Promise.all([getBuiltinSkills.call(this),this.listCustomSkills()]);if(!built.success)return built;if(!custom.success)return custom;return{success:true,data:[...built.data,...custom.data.map(value=>typeof value==="object"&&value?{...value,custom:true}:value)]}};
export interface CareerCraftClient{listResumeVersions(personaId:string):CommandPromise<"list_resume_versions">;diffResumeVersions(leftVersionId:string,rightVersionId:string):CommandPromise<"diff_resume_versions">;restoreResumeVersion(personaId:string,versionId:string):CommandPromise<"restore_resume_version">}
export interface CareerCraftClient{exportPortableBackup(destinationPath:string,acknowledgeUnencrypted:true):CommandPromise<"export_portable_backup">;inspectPortableBackup(archivePath:string):CommandPromise<"inspect_portable_backup">;importPortableBackup(archivePath:string,confirmed:true):CommandPromise<"import_portable_backup">}
export interface CareerCraftClient{importFile(fileName:string,base64Content:string):CommandPromise<"import_file">;chatRefineResume(personaId:string,instruction:string,instructionType?:"leadership"|"metrics"|"concise"|"technical_depth"|"job_alignment"|"general",confirm?:boolean,baseVersionId?:string,proposalId?:string,contentHash?:string):CommandPromise<"chat_refine_resume">}
export interface CareerCraftClient{collectJobUrl(url:string):CommandPromise<"collect_job_url">}
Object.assign(CareerCraftClient.prototype,{listResumeVersions(this:CareerCraftClient,personaId:string){return this.command("list_resume_versions",{personaId})},diffResumeVersions(this:CareerCraftClient,leftVersionId:string,rightVersionId:string){return this.command("diff_resume_versions",{leftVersionId,rightVersionId})},restoreResumeVersion(this:CareerCraftClient,_personaId:string,versionId:string){return this.command("restore_resume_version",{versionId})}});
Object.assign(CareerCraftClient.prototype,{exportPortableBackup(this:CareerCraftClient,destinationPath:string,acknowledgeUnencrypted:true){return this.command("export_portable_backup",{destinationPath,acknowledgeUnencrypted})},inspectPortableBackup(this:CareerCraftClient,archivePath:string){return this.command("inspect_portable_backup",{archivePath})},importPortableBackup(this:CareerCraftClient,archivePath:string,confirmed:true){return this.command("import_portable_backup",{archivePath,confirmed})}});
export interface CareerCraftClient{startBackgroundTask(request:BackgroundTaskRequest):CommandPromise<"start_background_task">;startBackgroundTask(operation:BackgroundTaskRequest["operation"]|string,payload?:BackgroundTaskRequest["payload"]|Record<string,unknown>):CommandPromise<"start_background_task">;getBackgroundTask(taskId:string):CommandPromise<"get_background_task">;cancelBackgroundTask(taskId:string):CommandPromise<"cancel_background_task">;listBackups():CommandPromise<"list_backups">;createBackup():CommandPromise<"create_backup">;restoreBackup(name:string):CommandPromise<"restore_backup">}
Object.assign(CareerCraftClient.prototype,{startBackgroundTask(this:CareerCraftClient,operationOrRequest:string|BackgroundTaskRequest,payload:Record<string,unknown>={}){const request=typeof operationOrRequest==="string"?{operation:operationOrRequest,payload}:operationOrRequest;return this.command("start_background_task",request)},getBackgroundTask(this:CareerCraftClient,taskId:string){return this.command("get_background_task",{taskId})},cancelBackgroundTask(this:CareerCraftClient,taskId:string){return this.command("cancel_background_task",{taskId})},listBackups(this:CareerCraftClient){return this.command("list_backups",undefined)},createBackup(this:CareerCraftClient){return this.command("create_backup",undefined)},restoreBackup(this:CareerCraftClient,name:string){return this.command("restore_backup",{name})}});
Object.assign(CareerCraftClient.prototype,{importFile(this:CareerCraftClient,fileName:string,base64Content:string){return this.command("import_file",{fileName,base64Content})},chatRefineResume(this:CareerCraftClient,personaId:string,instruction:string,instructionType?:"leadership"|"metrics"|"concise"|"technical_depth"|"job_alignment"|"general",confirm?:boolean,baseVersionId?:string,proposalId?:string,contentHash?:string){return this.command("chat_refine_resume",{personaId,instruction,...(instructionType&&!confirm?{instructionType}:{}),...(confirm===undefined?{}:{confirm}),...(baseVersionId?{baseVersionId}:{}),...(proposalId?{proposalId}:{}),...(contentHash?{contentHash}:{})})}});
export interface CareerCraftClient{getJobStatusEvents(matchId:string):CommandPromise<"get_job_status_events">}
export interface CareerCraftClient{updateMatchStatusVersioned(matchId:string,status:string,expectedVersion:number):CommandPromise<"update_match_status">}
Object.assign(CareerCraftClient.prototype,{getJobStatusEvents(this:CareerCraftClient,matchId:string){return this.command("get_job_status_events",{matchId})},updateMatchStatusVersioned(this:CareerCraftClient,matchId:string,status:string,expectedVersion:number){return this.command("update_match_status",{matchId,status,expectedVersion})}});
export interface CareerCraftClient{checkUpdate():CommandPromise<"check_update">;downloadUpdate():CommandPromise<"download_update">;installUpdate():CommandPromise<"install_update">}
Object.assign(CareerCraftClient.prototype,{checkUpdate(this:CareerCraftClient){return this.command("check_update",undefined)},downloadUpdate(this:CareerCraftClient){return this.command("download_update",undefined)},installUpdate(this:CareerCraftClient){return this.command("install_update",undefined)}});
Object.assign(CareerCraftClient.prototype,{collectJobUrl(this:CareerCraftClient,url:string){return this.command("collect_job_url",{url})}});
export function unwrap<T extends Json|Json[]>(result:ApiResult<T>):T{if(!result.success)throw result.error;return result.data}export const api=new CareerCraftClient();
