import type { ResumeInstructionType, WorkspaceDataSource } from "../../api/data-source";

type Obj=Record<string,unknown>;
export interface RefinementMeta{provider?:string;model?:string;fallback?:boolean;cachePolicy?:string;promptVersion?:string}
export interface RefinementSnapshot{phase:"started"|"progress"|"completed"|"failed"|"cancelled";progress?:number;text:string;message:string;meta:RefinementMeta;result?:Obj;retryable?:boolean}
const safeError=(error:unknown)=>{const value=(error&&typeof error==="object"?error:{})as Obj;const rawMessage=typeof value.message==="string"?value.message:"";const code=typeof value.code==="string"?value.code:"UNAVAILABLE";const lower=rawMessage.toLowerCase();const kind=lower.startsWith("timeout:")||lower.includes("timed out")?"TIMEOUT":lower.startsWith("rate_limited:")?"RATE_LIMITED":code;const messages:Record<string,string>={CANCELLED:"操作已取消",VALIDATION:"请求内容不完整，请检查后重试",CONFLICT:"简历已发生变化，请重新生成预览",RATE_LIMITED:"服务繁忙，请稍后重试",TIMEOUT:"响应超时，请重试（长文调优可能需要更久）",UNAVAILABLE:"AI 服务暂时不可用，请重试"};const detail=rawMessage.includes("must be valid JSON")?"模型返回格式异常，请重试":rawMessage.includes("unknown experience")?"模型引用了不存在的经历，请重试":rawMessage.includes("empty refinement")||rawMessage.includes("no experience updates")?"模型未产出可用调优内容，请换个要求重试":"";return{message:detail||messages[kind]||messages.UNAVAILABLE||"AI 服务暂时不可用，请重试",retryable:["RATE_LIMITED","TIMEOUT","UNAVAILABLE","TRANSPORT"].includes(kind)}};
const object=(value:unknown):Obj=>value&&typeof value==="object"&&!Array.isArray(value)?value as Obj:{};

export class RefinementTaskController{
 private generation=0;private taskId="";private lastSequence=-1;private text="";private meta:RefinementMeta={};
 constructor(private readonly source:WorkspaceDataSource,private readonly emit:(value:RefinementSnapshot)=>void,private readonly delay=(ms:number)=>new Promise<void>(resolve=>setTimeout(resolve,ms))){ }
 async start(personaId:string,instruction:string,instructionType:ResumeInstructionType){const generation=++this.generation;if(this.taskId)void this.source.cancelTask?.(this.taskId);this.taskId="";this.lastSequence=-1;this.text="";this.meta={};const taskId=await this.source.startTask("chat_refine_resume",{personaId,instruction,instructionType});if(generation!==this.generation){void this.source.cancelTask?.(taskId);return}this.taskId=taskId;this.emit({phase:"started",progress:0,text:"",message:"任务已提交",meta:{}});await this.poll(generation,taskId)}
 async cancel(){++this.generation;const id=this.taskId;this.taskId="";if(id)await this.source.cancelTask?.(id);this.emit({phase:"cancelled",text:this.text,message:"操作已取消，未保存任何修改",meta:this.meta})}
 invalidate(){++this.generation;const id=this.taskId;this.taskId="";if(id)void this.source.cancelTask?.(id)}
 private async poll(generation:number,taskId:string){for(;;){if(generation!==this.generation||taskId!==this.taskId)return;let task:Obj;try{task=object(await this.source.getTask?.(taskId))}catch(error){if(generation!==this.generation)return;const safe=safeError(error);this.emit({phase:"failed",text:this.text,message:safe.message,retryable:safe.retryable,meta:this.meta});return}if(String(task.taskId??taskId)!==taskId){await this.delay(50);continue}this.consume(Array.isArray(task.events)?task.events:[]);if(generation!==this.generation||taskId!==this.taskId)return;const state=String(task.state??"progress") as RefinementSnapshot["phase"];const progress=typeof task.progress==="number"?task.progress:undefined;const result=object(task.result);if(state==="completed"){this.readMeta(result);this.emit({phase:"completed",progress,text:this.text,message:"调优预览已生成",meta:this.meta,result});return}if(state==="failed"){const safe=safeError(task.error);this.emit({phase:"failed",text:this.text,message:safe.message,retryable:safe.retryable,meta:this.meta});return}if(state==="cancelled"){this.emit({phase:"cancelled",text:this.text,message:"操作已取消，未保存任何修改",meta:this.meta});return}this.emit({phase:state==="started"?"started":"progress",progress,text:this.text,message:progress===undefined?"等待模型响应":"正在生成调优预览",meta:this.meta});await this.delay(50)}}
 private consume(values:unknown[]){values.map((raw,index)=>({event:object(raw),sequence:typeof object(raw).sequence==="number"?Number(object(raw).sequence):index})).sort((a,b)=>a.sequence-b.sequence).forEach(({event,sequence})=>{if(sequence<=this.lastSequence)return;this.lastSequence=sequence;const kind=String(event.kind??"");if(kind==="delta"&&typeof event.text==="string")this.text+=event.text;if(kind==="started"){if(typeof event.provider==="string")this.meta.provider=event.provider;if(typeof event.model==="string")this.meta.model=event.model}if(kind==="retrying")this.meta.fallback=true})}
 private readMeta(result:Obj){if(typeof result.promptVersion==="string")this.meta.promptVersion=result.promptVersion;if(typeof result.cachePolicy==="string")this.meta.cachePolicy=result.cachePolicy;if(typeof result.provider==="string")this.meta.provider=result.provider;if(typeof result.model==="string")this.meta.model=result.model;if(typeof result.fallbackUsed==="boolean")this.meta.fallback=result.fallbackUsed}
}
