import{open,save}from"@tauri-apps/plugin-dialog";
import{api,unwrap}from"../../api/client";
import type{V2Actions,WorkspaceDataSource}from"../../api/data-source";
import type{TaskStore}from"../../shared/state/tasks";
const message=(error:unknown)=>typeof error==="object"&&error!==null&&"message"in error?String(error.message):"操作失败，请重试。";
const fail=(tasks:TaskStore,label:string,error:unknown)=>tasks.upsert({id:crypto.randomUUID(),label,phase:"failed",message:message(error),retryable:true});
const esc=(value:string)=>value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
const size=(bytes:number)=>bytes<1024?`${bytes} B`:bytes<1024*1024?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1024/1024).toFixed(1)} MB`;
export function bind(root:HTMLElement,source:WorkspaceDataSource&V2Actions,tasks:TaskStore,reload:()=>Promise<void>){
 root.querySelectorAll<HTMLElement>("[data-edit-provider]").forEach(node=>{const button=document.createElement("button");button.className="ghost danger-text";button.textContent="删除";button.addEventListener("click",async()=>{try{await source.deleteProvider(node.dataset.editProvider??"");await reload()}catch(error){fail(tasks,"删除服务商",error)}});node.after(button)});
 root.querySelectorAll<HTMLButtonElement>(".settings-group button:disabled").forEach(button=>{if(button.textContent?.includes("备份")){button.disabled=false;button.title="";button.addEventListener("click",async()=>{try{unwrap(await api.createBackup());tasks.upsert({id:crypto.randomUUID(),label:"创建备份",phase:"completed",message:"本地备份已创建。",progress:100})}catch(error){fail(tasks,"创建备份",error)}})}else if(button.textContent?.includes("恢复")){button.disabled=false;button.title="";button.addEventListener("click",async()=>{try{const values=unwrap(await api.listBackups())as Record<string,unknown>[];if(!values.length)throw new Error("没有可恢复的备份");const modal=document.createElement("div");modal.className="modal-backdrop";modal.innerHTML=`<section class="onboarding" role="dialog" aria-modal="true"><h1>选择备份</h1>${values.map(value=>{const name=String(value.name??"");return`<button class="content-row" data-restore-name="${esc(name)}"><span><strong>${esc(name)}</strong><small>${size(Number(value.size??0))}</small></span></button>`}).join("")}<button class="secondary" data-close-backup>取消</button></section>`;root.append(modal);modal.querySelector("[data-close-backup]")?.addEventListener("click",()=>modal.remove());modal.querySelectorAll<HTMLElement>("[data-restore-name]").forEach(item=>item.addEventListener("click",async()=>{const name=item.dataset.restoreName??"";if(!confirm(`确定恢复备份 ${name}？\n当前数据库会保留为恢复前副本，恢复将在重新启动 CareerCraft 后生效。`))return;const result=unwrap(await api.restoreBackup(name))as Record<string,unknown>;modal.remove();if(result.restartRequired===true)alert("备份已验证并准备完成。请关闭 CareerCraft 后重新打开，恢复才会生效。")}))}catch(error){fail(tasks,"恢复备份",error)}})}})
}
const filters=[{name:"CareerCraft 数据包",extensions:["ccbackup","zip"]}];
const hash=(value:string)=>`<code title="${esc(value)}">${esc(value)}</code>`;
export function bindPortable(root:HTMLElement,source:V2Actions,tasks:TaskStore){
 root.querySelector<HTMLButtonElement>("[data-export-portable]")?.addEventListener("click",async()=>{const destinationPath=await save({defaultPath:`CareerCraft-${new Date().toISOString().slice(0,10)}.ccbackup`,filters});if(!destinationPath)return;const modal=document.createElement("div");modal.className="modal-backdrop";modal.innerHTML=`<section class="onboarding" role="dialog" aria-modal="true"><h1>导出迁移数据包</h1><p class="warning" role="alert"><strong>敏感履历数据未加密。</strong>任何获得此文件的人都可能读取其中的经历、简历和岗位数据。</p><p>AI 服务密钥不会包含在数据包内。</p><label><input type="checkbox" data-export-ack> 我了解并接受未加密风险</label><button class="primary" data-confirm-export disabled>确认导出</button><button class="ghost" data-cancel-portable>取消</button></section>`;root.append(modal);const ack=modal.querySelector<HTMLInputElement>("[data-export-ack]")!,button=modal.querySelector<HTMLButtonElement>("[data-confirm-export]")!;ack.addEventListener("change",()=>button.disabled=!ack.checked);modal.querySelector("[data-cancel-portable]")?.addEventListener("click",()=>modal.remove());button.addEventListener("click",async()=>{if(!ack.checked)return;button.disabled=true;try{const result=await source.exportPortableBackup(destinationPath);modal.remove();tasks.upsert({id:crypto.randomUUID(),label:"导出数据包",phase:"completed",message:`数据包已导出（数据库校验 ${result.manifest.databaseSha256.slice(0,12)}…）`,progress:100})}catch(error){button.disabled=false;fail(tasks,"导出数据包",error)}})});
 root.querySelector<HTMLButtonElement>("[data-import-portable]")?.addEventListener("click",async()=>{const archivePath=await open({multiple:false,filters});if(!archivePath)return;try{const preview=await source.inspectPortableBackup(archivePath),modal=document.createElement("div"),counts=Object.entries(preview.recordCounts);modal.className="modal-backdrop";modal.innerHTML=`<section class="onboarding" role="dialog" aria-modal="true"><h1>检查数据包</h1><p class="status-label">校验完成；未修改当前用户数据库，临时候选文件已清理</p><dl><dt>应用版本</dt><dd>${esc(preview.manifest.appVersion)}</dd><dt>数据库结构版本</dt><dd>${preview.manifest.schemaVersion}</dd><dt>数据库 SHA-256（仅用于完整性校验）</dt><dd>${hash(preview.manifest.databaseSha256)}</dd><dt>设置 SHA-256（仅用于完整性校验）</dt><dd>${hash(preview.manifest.settingsSha256)}</dd><dt>记录数</dt><dd>${counts.length?counts.map(([name,count])=>`${esc(name)}：${count}`).join("；"):"0"}</dd></dl><p class="warning">哈希不能证明数据包来源可信。仅恢复你确认来源的数据包；恢复将在重启后生效，当前数据库会先创建安全备份。</p><button class="primary" data-confirm-import>确认恢复</button><button class="ghost" data-cancel-portable>取消</button></section>`;root.append(modal);modal.querySelector("[data-cancel-portable]")?.addEventListener("click",()=>modal.remove());modal.querySelector<HTMLButtonElement>("[data-confirm-import]")?.addEventListener("click",async event=>{if(!confirm("再次确认恢复此数据包？当前数据不会立即被覆盖，并会保留安全备份。"))return;const button=event.currentTarget as HTMLButtonElement;button.disabled=true;try{const result=await source.importPortableBackup(archivePath);modal.remove();tasks.upsert({id:crypto.randomUUID(),label:"导入数据包",phase:"completed",message:result.restartRequired?"数据包已验证并暂存，请重启应用完成恢复。":"数据包已验证。",progress:100})}catch(error){button.disabled=false;fail(tasks,"导入数据包",error)}})}catch(error){fail(tasks,"检查数据包",error)}})
}
