import type { LearningExperienceDraft, SkillLearningActions, WorkspaceDataSource } from "../../api/data-source";
import type { TaskStore } from "../../shared/state/tasks";
import { renderSkillDialog, renderWhatIfDialog } from "../pages";
type Source = WorkspaceDataSource & SkillLearningActions;
const report=(tasks:TaskStore,label:string,phase:"completed"|"failed",message:string)=>tasks.upsert({id:crypto.randomUUID(),label,phase,message,...(phase==="completed"?{progress:100}:{retryable:true})});
export function bind(root:HTMLElement,source:Source,tasks:TaskStore,reload:()=>Promise<void>){
 const toast=(message:string)=>{root.querySelector("[data-toast]")?.remove();const node=document.createElement("div");node.dataset.toast="true";node.setAttribute("role","status");node.setAttribute("aria-live","polite");node.className="status-label";node.textContent=message;root.append(node);setTimeout(()=>node.remove(),2500)};
 const close=()=>root.querySelector(".modal-backdrop:last-child")?.remove();
 const wire=()=>{
  root.querySelector<HTMLElement>("[data-close-overlay]")?.addEventListener("click",close);
  root.querySelector<HTMLFormElement>("[data-skill-form]")?.addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget as HTMLFormElement;const v=new FormData(form);try{await source.saveCustomSkill({id:form.dataset.id||undefined,name:String(v.get("name")),category:String(v.get("category")),level:Number(v.get("level"))});close();await reload()}catch(error){report(tasks,"保存技能","failed",(error as Error).message)}});
  root.querySelector<HTMLFormElement>("[data-what-if-form]")?.addEventListener("submit",async event=>{event.preventDefault();const v=new FormData(event.currentTarget as HTMLFormElement);const list=(name:string)=>String(v.get(name)).split(/[,，]/).map(x=>x.trim()).filter(Boolean);try{const result=await source.simulateWhatIf(list("required"),list("current"),list("hypothetical"));report(tasks,"假设分析","completed",`预计匹配变化：${JSON.stringify(result)}`);close()}catch(error){report(tasks,"假设分析","failed",(error as Error).message)}});
  const whatIf=root.querySelector<HTMLFormElement>("[data-what-if-form]");if(whatIf){const output=document.createElement("output");output.dataset.whatIfResult="true";output.setAttribute("aria-live","polite");whatIf.querySelector(".dialog-actions")?.before(output);let timer=0,request=0;whatIf.addEventListener("input",()=>{clearTimeout(timer);const current=++request;timer=window.setTimeout(async()=>{const v=new FormData(whatIf);const list=(name:string)=>String(v.get(name)).split(/[,，]/).map(x=>x.trim()).filter(Boolean);try{const result=await source.simulateWhatIf(list("required"),list("current"),list("hypothetical"))as Record<string,unknown>;if(current===request)output.textContent=`实时变化：${String(result.delta??0)} 分` }catch(error){if(current===request)output.textContent=`暂时无法计算：${(error as Error).message}`}},150)})}
 };
 const mount=(html:string)=>{root.insertAdjacentHTML("beforeend",html);wire()};
 root.querySelector<HTMLElement>('[data-action="add-skill"]')?.addEventListener("click",()=>mount(renderSkillDialog()));
 root.querySelector<HTMLElement>("[data-what-if]")?.addEventListener("click",()=>mount(renderWhatIfDialog()));
 let searchTimer=0;root.querySelector<HTMLInputElement>("[data-skill-search]")?.addEventListener("input",event=>{clearTimeout(searchTimer);const query=(event.currentTarget as HTMLInputElement).value;searchTimer=window.setTimeout(async()=>{try{const values=await source.searchSkills(query);root.querySelector("[data-skill-search-results]")?.remove();const host=document.createElement("section");host.dataset.skillSearchResults="true";host.setAttribute("aria-live","polite");host.innerHTML=values.length?values.map(x=>`<button class="content-row" data-skill-detail="${x.id.replace(/[&<>\"]/g,"")}">${x.name.replace(/[&<>]/g,"")}</button>`).join(""):'<p class="empty-state">没有匹配技能。</p>';root.querySelector("[data-skill-search]")?.closest(".toolbar")?.after(host);report(tasks,"技能搜索","completed",`找到 ${values.length} 项技能。`)}catch(error){report(tasks,"技能搜索","failed",(error as Error).message)}},180)});
 root.querySelectorAll<HTMLElement>("[data-edit-skill]").forEach(node=>node.addEventListener("click",async()=>{const skill=(await source.load()).skills.find(x=>x.id===node.dataset.editSkill);if(skill)mount(renderSkillDialog(skill))}));
 root.querySelectorAll<HTMLElement>("[data-delete-skill]").forEach(node=>node.addEventListener("click",async()=>{try{await source.deleteCustomSkill(node.dataset.deleteSkill??"");await reload()}catch(error){report(tasks,"删除技能","failed",(error as Error).message)}}));
 root.querySelectorAll<HTMLSelectElement>("[data-learning-status]").forEach(node=>node.addEventListener("change",async()=>{const id=node.dataset.learningStatus??"",item=(await source.load()).learning.find(x=>x.id===id),completionNote=node.value==="completed"?prompt("请填写学习完成说明（必填）")?.trim():undefined;if(node.value==="completed"&&!completionNote){report(tasks,"更新学习进度","failed","完成学习时必须填写完成说明。");return}try{await source.updateLearning(id,node.value,item?.version??1,completionNote);await reload()}catch(error){report(tasks,"更新学习进度","failed",(error as Error).message)}}));
 root.querySelectorAll<HTMLElement>("[data-complete-learning]").forEach(node=>node.addEventListener("click",()=>{const row=node.closest<HTMLElement>("[data-learning-row]");const title=row?.querySelector("strong")?.textContent?.trim()||"学习成果";root.insertAdjacentHTML("beforeend",`<div class="modal-backdrop" data-learning-draft><form class="onboarding"><h1>编辑经历草稿</h1><p>本步骤只生成待确认草稿，不会进入正式经历。</p><label>标题<input name="title" required value="${title.replace(/&/g,"&amp;").replace(/"/g,"&quot;")}"></label><label>组织/来源<input name="organization" required value="学习计划"></label><label>经历说明<textarea name="rawDescription" required>完成 ${title.replace(/&/g,"&amp;").replace(/</g,"&lt;")}</textarea></label><div class="dialog-actions"><button type="button" class="ghost" data-cancel-learning-draft>取消</button><button class="primary">生成待确认草稿</button></div></form></div>`);const modal=root.querySelector<HTMLElement>("[data-learning-draft]")!;modal.querySelector("[data-cancel-learning-draft]")?.addEventListener("click",()=>modal.remove());modal.querySelector("form")?.addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget as HTMLFormElement,v=new FormData(form),submit=form.querySelector<HTMLButtonElement>('button[type="submit"],button.primary');if(submit)submit.disabled=true;try{const draft=await source.completeLearning(node.dataset.completeLearning??"",{title:String(v.get("title")),organization:String(v.get("organization")),rawDescription:String(v.get("rawDescription"))});showPendingDraft(modal,draft)}catch(error){if(submit)submit.disabled=false;report(tasks,"生成经历草稿","failed",(error as Error).message)}})}));
 function showPendingDraft(modal:HTMLElement,draft:LearningExperienceDraft){const sourceTitle=(draft.sourceSnapshot?.title??draft.sourceLearningTitle).replace(/&/g,"&amp;").replace(/</g,"&lt;");modal.innerHTML=`<section class="onboarding" role="dialog" aria-modal="true"><p class="eyebrow">待确认</p><h1>${draft.title.replace(/&/g,"&amp;").replace(/</g,"&lt;")}</h1><p>${draft.rawDescription.replace(/&/g,"&amp;").replace(/</g,"&lt;")}</p><p class="helper">来源快照：${sourceTitle}。原学习路径删除后仍保留审计快照。</p><p class="helper">当前仍是草稿，确认后才进入正式经历；放弃会标记为 discarded，不用于简历或岗位匹配。</p><div class="dialog-actions"><button class="ghost" data-discard-learning-experience>放弃草稿</button><button class="primary" data-confirm-learning-experience>确认加入经历</button></div></section>`;const resolve=async(status:"confirmed"|"discarded")=>{modal.querySelectorAll<HTMLButtonElement>("button").forEach(x=>x.disabled=true);try{await source.resolveLearningExperience(draft,status);report(tasks,status==="confirmed"?"确认经历":"放弃经历草稿","completed",status==="confirmed"?"经历已确认并加入正式经历库。":"草稿已放弃，来源快照保留用于审计。");modal.remove();await reload()}catch(error){modal.querySelectorAll<HTMLButtonElement>("button").forEach(x=>x.disabled=false);report(tasks,"处理经历草稿","failed",(error as Error).message)}};modal.querySelector("[data-confirm-learning-experience]")?.addEventListener("click",()=>void resolve("confirmed"));modal.querySelector("[data-discard-learning-experience]")?.addEventListener("click",()=>void resolve("discarded"))}
 root.addEventListener("click",event=>{const node=(event.target as Element).closest<HTMLElement>("[data-skill-detail]");if(node&&root.contains(node))void openSkill(node.dataset.skillDetail??"")});
 async function openSkill(id:string){try{const skill=(await source.load()).skills.find(x=>x.id===id);if(!skill)return;const resources=skill.resources?.length?skill.resources:await source.getSkillResources(skill.id);const modal=document.createElement("div");modal.className="modal-backdrop";const section=document.createElement("section");section.className="onboarding";section.setAttribute("role","dialog");section.setAttribute("aria-modal","true");const title=document.createElement("h1");title.textContent=skill.name;const description=document.createElement("p");description.textContent=skill.description||"暂无技能说明。";section.append(title,description);for(const item of resources){const row=document.createElement("article"),summary=document.createElement("p"),actions=document.createElement("p"),copy=document.createElement("button"),open=document.createElement("button");row.className="document-section";summary.textContent=`${item.title} · ${item.source} · ${item.estimatedHours} 小时`;copy.type="button";copy.className="ghost";copy.dataset.copyResource=item.url;copy.textContent="复制链接";copy.setAttribute("aria-label",`复制 ${item.title} 的学习链接`);open.type="button";open.className="secondary";open.dataset.openResource=item.url;open.textContent="安全打开";open.setAttribute("aria-label",`打开 ${item.title}`);actions.append(copy,open);row.append(summary,actions);section.append(row)}const closeButton=document.createElement("button");closeButton.textContent="关闭";closeButton.addEventListener("click",()=>modal.remove());section.append(closeButton);modal.append(section);root.append(modal)}catch(error){report(tasks,"技能详情","failed",(error as Error).message)}}
 root.querySelector<HTMLSelectElement>("[data-skill-category]")?.addEventListener("change",event=>root.querySelectorAll<HTMLElement>("[data-skill-row]").forEach(row=>row.hidden=Boolean((event.currentTarget as HTMLSelectElement).value&&row.dataset.category!==(event.currentTarget as HTMLSelectElement).value)));
 root.querySelector<HTMLSelectElement>("[data-learning-source]")?.addEventListener("change",event=>root.querySelectorAll<HTMLElement>("[data-learning-row]").forEach(row=>row.hidden=Boolean((event.currentTarget as HTMLSelectElement).value&&row.dataset.source!==(event.currentTarget as HTMLSelectElement).value)));
 root.querySelector<HTMLSelectElement>("[data-job-filter]")?.addEventListener("change",event=>root.querySelectorAll<HTMLElement>("[data-job-row]").forEach(row=>row.hidden=Boolean((event.currentTarget as HTMLSelectElement).value&&row.dataset.status!==(event.currentTarget as HTMLSelectElement).value)));
 root.addEventListener("click",event=>{const copy=(event.target as Element).closest<HTMLElement>("[data-copy-resource]");if(copy&&root.contains(copy))void(async()=>{try{await navigator.clipboard.writeText(copy.dataset.copyResource??"");toast("链接已复制。") }catch(error){report(tasks,"复制资源链接","failed",(error as Error).message)}})();const open=(event.target as Element).closest<HTMLElement>("[data-open-resource]");if(open&&root.contains(open))void(async()=>{try{await source.openResource(open.dataset.openResource??"");toast("已安全打开资源。") }catch(error){report(tasks,"打开资源","failed",(error as Error).message)}})()});
}
