-- DB-GOLD-001 / CC-FR-002,004,005,009,011,012,015,023
-- Exact SQLite DDL compiled from src/models/entities.py on 2026-07-20.
CREATE TABLE experiences (id VARCHAR(36) NOT NULL, user_id VARCHAR(36) NOT NULL, type VARCHAR(20) NOT NULL, title VARCHAR(200) NOT NULL, organization VARCHAR(200), start_date DATE, end_date DATE, raw_description TEXT NOT NULL, structured_achievements JSON, skills_demonstrated JSON, metrics JSON, status VARCHAR(20) NOT NULL, version INTEGER NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE job_descs (id VARCHAR(36) NOT NULL, raw_text TEXT NOT NULL, title VARCHAR(200), company VARCHAR(200), years_of_experience VARCHAR(50), salary_range VARCHAR(100), location VARCHAR(200), job_type VARCHAR(50), education_requirement VARCHAR(100), responsibilities JSON, benefits JSON, url VARCHAR(500), parsed_skills JSON, source VARCHAR(50), created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE personas (id VARCHAR(36) NOT NULL, user_id VARCHAR(36) NOT NULL, name VARCHAR(100) NOT NULL, is_default BOOLEAN NOT NULL, identity_statement TEXT, career_narrative TEXT, tone_style VARCHAR(50), capability_weights JSON, target_job_profiles JSON, max_experiences INTEGER NOT NULL, preferred_model VARCHAR(100), created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE skill_nodes (id VARCHAR(36) NOT NULL, name VARCHAR(100) NOT NULL, category VARCHAR(50), description TEXT, parent_id VARCHAR(36), aliases JSON, resources JSON, vector_embedding VARCHAR(36), created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id), UNIQUE (name), FOREIGN KEY(parent_id) REFERENCES skill_nodes (id) ON DELETE SET NULL);
CREATE TABLE uploaded_files (id VARCHAR(36) NOT NULL, user_id VARCHAR(36) NOT NULL, filename VARCHAR(255) NOT NULL, file_type VARCHAR(50) NOT NULL, content_preview TEXT, extracted_count INTEGER NOT NULL, status VARCHAR(20) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id));
CREATE TABLE job_matches (id VARCHAR(36) NOT NULL, persona_id VARCHAR(36) NOT NULL, job_desc_id VARCHAR(36) NOT NULL, match_score INTEGER NOT NULL, matched_skills JSON, missing_skills JSON, score_breakdown JSON, notes TEXT, ai_analysis TEXT, tracking_status VARCHAR(20) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id), FOREIGN KEY(persona_id) REFERENCES personas (id) ON DELETE CASCADE, FOREIGN KEY(job_desc_id) REFERENCES job_descs (id) ON DELETE CASCADE);
CREATE TABLE learning_paths (id VARCHAR(36) NOT NULL, persona_id VARCHAR(36) NOT NULL, target_gap VARCHAR(200), items JSON, source_type VARCHAR(20), status VARCHAR(20) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id), FOREIGN KEY(persona_id) REFERENCES personas (id) ON DELETE CASCADE);
CREATE TABLE role_experience_weights (id VARCHAR(36) NOT NULL, persona_id VARCHAR(36) NOT NULL, experience_id VARCHAR(36) NOT NULL, relevance_score FLOAT NOT NULL, reframed_summary TEXT, highlighted_skills JSON, user_overridden BOOLEAN NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id), FOREIGN KEY(persona_id) REFERENCES personas (id) ON DELETE CASCADE, FOREIGN KEY(experience_id) REFERENCES experiences (id) ON DELETE CASCADE);
CREATE TABLE job_match_experience_reframes (id VARCHAR(36) NOT NULL, job_match_id VARCHAR(36) NOT NULL, experience_id VARCHAR(36) NOT NULL, original_summary TEXT NOT NULL, reframed_summary TEXT NOT NULL, reframing_strategy TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id), FOREIGN KEY(job_match_id) REFERENCES job_matches (id) ON DELETE CASCADE, FOREIGN KEY(experience_id) REFERENCES experiences (id) ON DELETE CASCADE);

-- Legacy ORM declares no explicit non-PK indexes. SQLite creates autoindexes for PK/UNIQUE.
