import{describe,expect,it,vi}from"vitest";
import{App}from"../../src/app";
import{experienceConflictIds,renderPage}from"../../src/features/pages";
import type{Experience,WorkspaceDataSource,WorkspaceSnapshot}from"../../src/api/data-source";
const wait=()=>new Promise(r=>setTimeout(r,20));
const empty:WorkspaceSnapshot={experiences:[],personas:[],jobs:[],resumes:[],skills:[],learning:[],providers:[]};
function source(snapshot:WorkspaceSnapshot=empty){return{load:vi.fn().mockResolvedValue(snapshot),addExperience:vi.fn(),deleteExperience:vi.fn(),updateExperience:vi.fn(),createPersona:vi.fn(),updatePersona:vi.fn(),deletePersona:vi.fn(),getFitScores:vi.fn().mockResolvedValue([]),setFitScore:vi.fn(),resetFitScore:vi.fn(),saveProvider:vi.fn(),testProvider:vi.fn(),startTask:vi.fn()}as unknown as WorkspaceDataSource&{updateExperience:ReturnType<typeof vi.fn>;resetFitScore:ReturnType<typeof vi.fn>}}
describe("P0 experience confirmation",()=>{
 it("creates a draft, permits preview edits, then confirms it",async()=>{localStorage.setItem("careercraft:onboarding-complete","true");const draft:Experience={id:"d1",version:1,title:"Draft",organization:"Org",period:"2024-01-01—",startDate:"2024-01-01",endDate:"",kind:"工作",original:"Raw",skills:[],status:"draft"};const s=source();(s.addExperience as ReturnType<typeof vi.fn>).mockResolvedValue(draft);const root=document.createElement("div");new App(root,s).mount();await wait();root.querySelector<HTMLButtonElement>('[data-action="add-experience"]')!.click();const form=root.querySelector<HTMLFormElement>('[data-experience-form]')!;for(const[name,value]of Object.entries({title:"Draft",organization:"Org",startDate:"2024-01-01",original:"Raw"}))form.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[name="${name}"]`)!.value=value;form.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));await wait();const confirm=root.querySelector<HTMLFormElement>("[data-draft-confirm]")!;expect(confirm).not.toBeNull();confirm.querySelector<HTMLInputElement>('[name="title"]')!.value="Edited";confirm.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));await wait();expect(s.updateExperience).toHaveBeenCalledWith(expect.objectContaining({id:"d1",title:"Edited",status:"confirmed"}))});
 it("shows backend overlap warning before confirmation",async()=>{localStorage.setItem("careercraft:onboarding-complete","true");const draft:Experience={id:"d-warning",version:1,title:"Overlap",organization:"Org",period:"2024-01—2024-12",kind:"工作",original:"Raw",skills:[],status:"draft",overlapExperienceIds:["existing"],warnings:[{code:"DATE_OVERLAP",experienceIds:["existing"]}]};const s=source();(s.addExperience as ReturnType<typeof vi.fn>).mockResolvedValue(draft);const root=document.createElement("div");new App(root,s).mount();await wait();root.querySelector<HTMLButtonElement>('[data-action="add-experience"]')!.click();const form=root.querySelector<HTMLFormElement>('[data-experience-form]')!;for(const[name,value]of Object.entries({title:"Overlap",organization:"Org",startDate:"2024-01-01",original:"Raw"}))form.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[name="${name}"]`)!.value=value;form.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));await wait();expect(root.querySelector("[data-draft-confirm] [role=alert]")?.textContent).toContain("日期与已有经历重叠");expect(s.updateExperience).not.toHaveBeenCalled()});
 it("discards an unconfirmed draft through lifecycle update",async()=>{localStorage.setItem("careercraft:onboarding-complete","true");const draft:Experience={id:"d2",version:1,title:"Draft",organization:"Org",period:"",kind:"项目",original:"Raw",skills:[],status:"draft"};const s=source();(s.addExperience as ReturnType<typeof vi.fn>).mockResolvedValue(draft);const root=document.createElement("div");new App(root,s).mount();await wait();root.querySelector<HTMLButtonElement>('[data-action="add-experience"]')!.click();const form=root.querySelector<HTMLFormElement>('[data-experience-form]')!;for(const[name,value]of Object.entries({title:"Draft",organization:"Org",startDate:"2024-01-01",original:"Raw"}))form.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[name="${name}"]`)!.value=value;form.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));await wait();root.querySelector<HTMLButtonElement>("[data-discard-draft]")!.click();await wait();expect(s.updateExperience).toHaveBeenCalledWith(expect.objectContaining({id:"d2",status:"discarded"}));expect(s.deleteExperience).not.toHaveBeenCalled()});
 it("recovers a persisted draft after remount and can confirm it",async()=>{localStorage.setItem("careercraft:onboarding-complete","true");const draft:Experience={id:"persisted",version:3,title:"Recovered",organization:"Org",period:"2024",kind:"工作",original:"Raw",skills:[],status:"draft"};const s=source({...empty,experiences:[draft]});const root=document.createElement("div");const app=new App(root,s);app.navigation.navigate("experiences");app.mount();await wait();expect(root.textContent).toContain("待确认");root.querySelector<HTMLButtonElement>("[data-confirm-existing-draft]")!.click();await wait();expect(s.updateExperience).toHaveBeenCalledWith(expect.objectContaining({id:"persisted",version:3,status:"confirmed"}))});
});
it("renders backend overlap warnings without recomputing dates",()=>{const experiences=[{id:"a",period:"",title:"A",organization:"",kind:"工作",original:"",skills:[],version:1,status:"confirmed",overlapExperienceIds:["b"],warnings:[{code:"DATE_OVERLAP",experienceIds:["b"]}]},{id:"b",period:"",title:"B",organization:"",kind:"工作",original:"",skills:[],version:1,status:"confirmed",overlapExperienceIds:["a"]}]as Experience[];expect([...experienceConflictIds(experiences)]).toEqual(["a","b"]);expect(renderPage("experiences",{...empty,experiences})).toContain("日期与其他经历重叠")});
it("loads actual fit values and resets an override",async()=>{localStorage.setItem("careercraft:onboarding-complete","true");const exp:Experience={id:"e",version:1,title:"E",organization:"",period:"",kind:"工作",original:"",skills:[],status:"confirmed"};const s=source({...empty,experiences:[exp],personas:[{id:"p",name:"P",targetRole:"R",positioning:"",fit:70}]});(s.getFitScores as ReturnType<typeof vi.fn>).mockResolvedValue([{experienceId:"e",score:77,overridden:true}]);const root=document.createElement("div");const app=new App(root,s);app.navigation.navigate("personas");app.mount();await wait();root.querySelector<HTMLButtonElement>("[data-fit-persona]")!.click();await wait();expect(root.querySelector<HTMLInputElement>('[name="e"]')!.value).toBe("77");root.querySelector<HTMLButtonElement>("[data-reset-fit]")!.click();await wait();expect(s.resetFitScore).toHaveBeenCalledWith("p","e")});
it("renders persisted resume markdown as escaped text",()=>{const html=renderPage("resumes",{...empty,resumes:[{id:"v",title:"Resume",persona:"p",template:"classic",version:2,updatedAt:"now",preview:"# Ada\n<img src=x onerror=1>"}]});expect(html).toContain("# Ada");expect(html).toContain("&lt;img");const root=document.createElement("div");root.innerHTML=html;expect(root.querySelector("img")).toBeNull()});
