import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import type { BackgroundTaskRequest, CheckUpdateDto, CommandMap, DownloadUpdateDto, InstallUpdateDto, JobStatusEventDto, LearningConversionDto, LearningConversionRequest, LearningProgressRequest, MatchStatusUpdateDto, PdfDto, ResumePreviewDto, ResumeRefineConfirmRequest, ResumeRefinePreviewRequest, SkillResourceDto, StructurePreviewDto } from "../../src/api/contracts";
const manifest = JSON.parse(readFileSync("contracts/commands/v3/commands.json", "utf8"));
describe("v3 contract gate", () => {
    it("keeps structure preview aligned", () => { expect(manifest.topLevelCommandCount).toBe(62);
expect(manifest.topLevelCommandsAdded[0][0]).toBe("previewResume");
const preview: ResumePreviewDto = { personaId: "p", template: "technical", markdown: "# P", contentHash: "h", selectedExperienceIds: [], fitScores: [], warnings: [] };
const pdf: PdfDto = { pdfBase64: "UERG", filename: "r.pdf", versionId: "v", template: "technical", contentHash: "h" };
const request: BackgroundTaskRequest = { operation: "structure_experience", payload: { rawDescription: "raw" } };
const response: StructurePreviewDto = { draft: { type: "certification", title: "Cert", organization: null, startDate: null, endDate: null, rawDescription: "raw", structuredAchievements: ["Passed"], skillsDemonstrated: ["Cloud"], industryTags: ["Technology"], educationLevel: "bachelor", status: "draft" }, promptVersion: "v1", provider: "mock", model: "mock", warnings: [] };
expect(preview.contentHash).toBe(pdf.contentHash);
expect(request.payload).toEqual({ rawDescription: "raw" });
expect(response.draft.type).toBe("certification");
});
    it("requires structured tuning fields", () => { const preview: ResumeRefinePreviewRequest = { personaId: "p", instructionType: "job_alignment", instruction: "optimize" };
const confirm: ResumeRefineConfirmRequest = { personaId: "p", instruction: "optimize", confirm: true, baseVersionId: "v", proposalId: "proposal", contentHash: "hash" };
const background: BackgroundTaskRequest = { operation: "chat_refine_resume", payload: preview };
const direct: CommandMap["chat_refine_resume"]["request"] = confirm;
expect(background.payload).toEqual(preview);
expect(direct.confirm).toBe(true);
});
    it("types learning conversion as an editable draft", () => { const request: LearningConversionRequest = { itemId: "item", experienceId: "exp", title: "Edited", organization: "Academy", rawDescription: "Built" };
const response: LearningConversionDto = { experienceId: "exp", converted: true, conversionId: "c", sourceSnapshot: { itemId: "item", pathId: "p", skillId: "s", title: "T", completionNote: "Done" }, draft: { id: "exp", version: 1, status: "draft", title: "Edited", organization: "Academy", rawDescription: "Built", sourceLearningTitle: "T", completionNote: "Done" } };
expect(request.title).toBe(response.draft.title);
});
    it("types audit resources and optimistic progress", () => { const event: JobStatusEventDto = { id: "1", matchId: "m", fromStatus: null, toStatus: "new", changedAt: "now" };
const resource: SkillResourceDto = { resourceId: "r", skillId: "s", kind: "course", title: "T", source: "official", url: "https://example.com", estimatedHours: 1 };
const progress: LearningProgressRequest = { pathId: "p", itemId: "i", status: "completed", expectedVersion: 3, completionNote: "Done" };
expect(event.fromStatus).toBeNull();
expect(resource.source).toBe("official");
expect(progress.expectedVersion).toBe(3);
});
    it("keeps match status CAS response exact", () => { const spec = manifest.responseExtensions.updateMatchStatus;
const response: MatchStatusUpdateDto = { id: "m", trackingStatus: "applied", eventId: 2, version: 4 };
expect(Object.keys(response).sort()).toEqual([...spec.responseRequired].sort());
const typed: CommandMap["update_match_status"]["response"] = { success: true, data: response };
expect(typed.data.version).toBe(4);
});
    it("types updater commands and exact runtime shapes", () => { expect(manifest.responseExtensions["checkUpdate|downloadUpdate|installUpdate"].disabledBehavior).toContain("UNAVAILABLE");
const unavailable: CheckUpdateDto = { available: false }, available: CheckUpdateDto = { available: true, version: "1.2.0", body: null, date: null }, download: DownloadUpdateDto = { staged: true, version: "1.2.0", bytes: 42 }, install: InstallUpdateDto = { installed: true, relaunchRequired: true, version: "1.2.0" };
const checkSlot: CommandMap["check_update"]["response"] = { success: true, data: available };
const downloadSlot: CommandMap["download_update"]["response"] = { success: true, data: download };
const installSlot: CommandMap["install_update"]["response"] = { success: true, data: install };
expect(unavailable.available).toBe(false);
expect(Object.keys(checkSlot.data).sort()).toEqual(["available", "body", "date", "version"]);
expect(Object.keys(downloadSlot.data).sort()).toEqual(["bytes", "staged", "version"]);
expect(Object.keys(installSlot.data).sort()).toEqual(["installed", "relaunchRequired", "version"]);
});
});
