import{beforeEach,describe,expect,it,vi}from"vitest";
import{App}from"../../src/app";import type{Experience,WorkspaceDataSource,WorkspaceSnapshot}from"../../src/api/data-source";
const empty:WorkspaceSnapshot={experiences:[],personas:[],jobs:[],resumes:[],skills:[],learning:[],providers:[]};const tick=()=>new Promise(r=>setTimeout(r,0));
const draft=(raw:string,overrides:Record<string,unknown>={})=>({type:"work",title:"Structured title",organization:"Example",startDate:"2024-01-01",endDate:null,rawDescription:raw,structuredAchievements:["Reduced MTTR by 30%"],skillsDemonstrated:["Incident management"],industryTags:["SaaS"],educationLevel:"none",status:"draft",...overrides});
function source(task:Record<string,unknown>|Error){const addExperience=vi.fn(async input=>({...input,id:"d1",version:1,skills:input.skillsDemonstrated??[],status:"draft"}as Experience));return{load:vi.fn().mockResolvedValue(empty),addExperience,deleteExperience:vi.fn(),createPersona:vi.fn(),updatePersona:vi.fn(),deletePersona:vi.fn(),getFitScores:vi.fn().mockResolvedValue([]),setFitScore:vi.fn(),saveProvider:vi.fn(),testProvider:vi.fn(),startTask:task instanceof Error?vi.fn().mockRejectedValue(task):vi.fn().mockResolvedValue("task-1"),getTask:vi.fn().mockResolvedValue(task),cancelTask:vi.fn().mockResolvedValue({state:"cancelled"})}}
async function open(s:ReturnType<typeof source>,raw:string){localStorage.setItem("careercraft:onboarding-complete","true");const root=document.createElement("div");new App(root,s as unknown as WorkspaceDataSource).mount();await tick();root.querySelector<HTMLButtonElement>('[data-action="add-experience"]')!.click();root.querySelector<HTMLTextAreaElement>('[name="original"]')!.value=raw;root.querySelector<HTMLButtonElement>("[data-structure-experience]")!.click();await tick();await tick();return root}
describe("W1 v3 experience structure",()=>{beforeEach(()=>localStorage.clear());
 it.each(["我负责供应链看板，把缺货率降低了 12%","Built an incident dashboard and reduced MTTR by 30%"])("reads nested result.draft and preserves raw: %s",async raw=>{const s=source({state:"completed",result:{draft:draft(raw),promptVersion:"v1",provider:"mock",model:"mock",warnings:[]}});const root=await open(s,raw);const form=root.querySelector<HTMLFormElement>('[data-phase="editablePreview"]')!;expect(form.querySelector<HTMLTextAreaElement>('[name="original"]')!.value).toBe(raw);form.querySelector<HTMLInputElement>('[name="title"]')!.value="Edited";form.querySelector<HTMLTextAreaElement>('[name="structuredAchievements"]')!.value="A\nB";form.querySelector<HTMLTextAreaElement>('[name="skillsDemonstrated"]')!.value="Rust\nSQL";form.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));await tick();expect(s.addExperience).toHaveBeenCalledWith(expect.objectContaining({title:"Edited",original:raw,structuredAchievements:["A","B"],skillsDemonstrated:["Rust","SQL"],status:"draft"}))});
 it("persists certification type end to end",async()=>{const raw="Passed cloud certification";const s=source({state:"completed",result:{draft:draft(raw,{type:"certification"})}});const root=await open(s,raw);expect(root.querySelector<HTMLSelectElement>('[name="kind"]')!.value).toBe("certification");root.querySelector<HTMLFormElement>("[data-experience-form]")!.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));await tick();expect(s.addExperience).toHaveBeenCalledWith(expect.objectContaining({kind:"认证",structuredAchievements:["Reduced MTTR by 30%"],skillsDemonstrated:["Incident management"]}))});
 it.each([{state:"failed",error:{message:"provider failed"}},{state:"completed",result:{draft:draft("raw",{type:"unknown"})}},{state:"completed",result:{draft:draft("raw",{title:""})} }])("enters error fallback for failed or invalid v3 result",async task=>{const root=await open(source(task as Record<string,unknown>),"raw");expect(root.querySelector('[data-phase="error"]')).not.toBeNull();expect(root.querySelector<HTMLTextAreaElement>('[name="original"]')!.value).toBe("raw")});
 it("accepts empty achievements and skills as editable preview",async()=>{const raw="partial extraction";const s=source({state:"completed",result:{draft:draft(raw,{structuredAchievements:[],skillsDemonstrated:[]})}});const root=await open(s,raw);expect(root.querySelector('[data-phase="editablePreview"]')).not.toBeNull()});
 it("accepts experienceType alias from backend drafts",async()=>{const raw="alias raw";const base=draft(raw);const aliased={...base,experienceType:base.type};delete (aliased as {type?:string}).type;const s=source({state:"completed",result:{draft:aliased}});const root=await open(s,raw);expect(root.querySelector('[data-phase="editablePreview"]')).not.toBeNull();expect(root.querySelector<HTMLSelectElement>('[name="kind"]')!.value).toBe("work")});
 it("cancel ignores a late completed response and never saves",async()=>{let resolve!:(v:Record<string,unknown>)=>void;const deferred=new Promise<Record<string,unknown>>(r=>resolve=r);const s=source({state:"progress"});s.getTask=vi.fn().mockReturnValue(deferred);const root=await open(s,"late raw");root.querySelector<HTMLButtonElement>("[data-cancel-structure]")!.click();await tick();resolve({state:"completed",result:{draft:draft("late raw")}});await tick();expect(s.cancelTask).toHaveBeenCalledWith("task-1");expect(root.querySelector('[data-phase="editablePreview"]')).toBeNull();expect(s.addExperience).not.toHaveBeenCalled()});
 it("escapes malicious nested draft fields",async()=>{const raw="safe";const root=await open(source({state:"completed",result:{draft:draft(raw,{title:'<img src=x onerror=1>',structuredAchievements:["<script>bad()</script>"]})}}),raw);expect(root.querySelector("img")).toBeNull();expect(root.querySelector("script")).toBeNull();expect(root.querySelector<HTMLInputElement>('[name="title"]')!.value).toContain("<img")});
 it("preserves whitespace and newline in raw text byte-for-byte through save",async()=>{const raw="  原文\n";const s=source({state:"completed",result:{draft:draft(raw)}});const root=await open(s,raw);root.querySelector<HTMLFormElement>("[data-experience-form]")!.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));await tick();expect(s.addExperience).toHaveBeenCalledWith(expect.objectContaining({original:raw}));expect((s.addExperience.mock.calls[0]?.[0] as Experience).original).toBe(raw)});
 it.each([["金融科技\n银行","master"],["Healthcare\nSaaS","bachelor"]])("edits and persists bilingual industry tags with education %s",async(tags,educationLevel)=>{const raw="structured profile";const s=source({state:"completed",result:{draft:draft(raw,{industryTags:["Initial"],educationLevel:"none"})}});const root=await open(s,raw);root.querySelector<HTMLTextAreaElement>('[name="industryTags"]')!.value=tags;root.querySelector<HTMLSelectElement>('[name="educationLevel"]')!.value=educationLevel;root.querySelector<HTMLFormElement>("[data-experience-form]")!.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));await tick();expect(s.addExperience).toHaveBeenCalledWith(expect.objectContaining({industryTags:tags.split("\n"),educationLevel}))});
});
