import{describe,expect,it,vi}from"vitest";import{RefinementTaskController}from"../../src/features/actions/resume-refinement";import{bind}from"../../src/features/actions/resume-extra";import{TaskStore}from"../../src/shared/state/tasks";import type{ResumeActions,WorkspaceDataSource,WorkspaceSnapshot}from"../../src/api/data-source";
const snapshot:WorkspaceSnapshot={experiences:[],personas:[{id:"p1",name:"P",targetRole:"R",positioning:"",fit:1}],jobs:[],resumes:[],skills:[],learning:[],providers:[]};
const source=(tasks:Record<string,unknown>[])=>({load:vi.fn().mockResolvedValue(snapshot),startTask:vi.fn().mockResolvedValue("task-new"),getTask:vi.fn().mockImplementation(async()=>tasks.shift()),cancelTask:vi.fn(),chatRefineResume:vi.fn(),generateResume:vi.fn(),previewResume:vi.fn(),listResumeVersions:vi.fn().mockResolvedValue([]),diffResumeVersions:vi.fn(),restoreResumeVersion:vi.fn()});
describe("W4 AI frontend gates",()=>{
 it("consumes real deltas once by taskId and sequence and exposes honest metadata",async()=>{const s=source([{taskId:"task-new",state:"progress",progress:null,events:[{kind:"delta",text:"C",sequence:2},{kind:"delta",text:"A",sequence:0},{kind:"started",provider:"openai",model:"gpt",attempt:1,sequence:1}]},{taskId:"task-new",state:"completed",progress:100,events:[{kind:"delta",text:"A",sequence:0},{kind:"started",provider:"openai",model:"gpt",sequence:1},{kind:"delta",text:"C",sequence:2},{kind:"delta",text:"!",sequence:3}],result:{refinedSummary:"AC!",baseVersionId:"v1",promptVersion:"resume-tuning-v1",cachePolicy:"no-store"}}]);const seen:any[]=[];const c=new RefinementTaskController(s as unknown as WorkspaceDataSource,x=>seen.push(x),async()=>{});await c.start("p1","concise","concise");expect(seen.at(-1).text).toBe("AC!");expect(seen.at(-1).meta).toMatchObject({provider:"openai",model:"gpt",promptVersion:"resume-tuning-v1",cachePolicy:"no-store"});expect(seen.some(x=>x.progress===undefined&&x.message.includes("等待"))).toBe(true)});
 it("cancels without a write and sanitizes errors",async()=>{const s=source([]);let release!:()=>void;s.getTask.mockImplementation(()=>new Promise(resolve=>{release=()=>resolve({taskId:"task-new",state:"failed",error:{code:"UNAVAILABLE",message:"secret",stack:"token=abc"},events:[]})}));const seen:any[]=[];const c=new RefinementTaskController(s as unknown as WorkspaceDataSource,x=>seen.push(x),async()=>{});const running=c.start("p1","x","general");await Promise.resolve();await c.cancel();release();await running;expect(s.cancelTask).toHaveBeenCalledWith("task-new");expect(s.chatRefineResume).not.toHaveBeenCalled();expect(JSON.stringify(seen)).not.toContain("secret");expect(JSON.stringify(seen)).not.toContain("token=abc")});
 it("renders five Chinese tuning choices plus English general and confirms the exact proposal",async()=>{const s=source([{taskId:"task-new",state:"completed",progress:100,events:[],result:{refinedSummary:"ok",baseVersionId:"v1",proposalId:"proposal-1",contentHash:"hash-1"}}]);const root=document.createElement("div");root.innerHTML='<section class="paper"></section>';bind(root,s as unknown as WorkspaceDataSource&ResumeActions,new TaskStore());root.querySelector<HTMLButtonElement>('[data-action="resume-refine"]')!.click();const labels=root.querySelector("select")!.textContent!;for(const value of["领导力","量化成果","精炼表达","技术深度","岗位对齐","General (English)"])expect(labels).toContain(value);const form=root.querySelector<HTMLFormElement>("[data-refine-form]")!;form.querySelector<HTMLSelectElement>("select")!.value="job_alignment";form.querySelector<HTMLTextAreaElement>("textarea")!.value="匹配岗位";form.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,0));expect(s.startTask).toHaveBeenCalledWith("chat_refine_resume",{personaId:"p1",instruction:"匹配岗位",instructionType:"job_alignment"});root.querySelector<HTMLButtonElement>("[data-confirm-refine]")!.click();await Promise.resolve();expect(s.chatRefineResume).toHaveBeenCalledWith("p1","匹配岗位",true,undefined,"v1","job_alignment","proposal-1","hash-1")});
 it("latest launch cancels the previous task",async()=>{const s=source([]);s.startTask.mockResolvedValueOnce("old").mockResolvedValueOnce("new");s.getTask.mockImplementation(async(id:string)=>id==="new"?{taskId:"new",state:"completed",events:[],result:{}}:new Promise(()=>{}));const c=new RefinementTaskController(s as unknown as WorkspaceDataSource,()=>{},async()=>{});void c.start("p1","first","general");await Promise.resolve();void c.start("p1","second","general");await Promise.resolve();expect(s.cancelTask).toHaveBeenCalledWith("old")});
});
