import{afterEach,beforeEach,describe,expect,it,vi}from"vitest";
import{open,save}from"@tauri-apps/plugin-dialog";
import{CareerCraftClient}from"../../src/api/client";
import type{V2Actions}from"../../src/api/data-source";
import type{CommandTransport}from"../../src/api/transport";
import{bindPortable}from"../../src/features/actions/settings";
import{TaskStore}from"../../src/shared/state/tasks";
vi.mock("@tauri-apps/plugin-dialog",()=>({open:vi.fn(),save:vi.fn()}));
const tick=()=>new Promise(resolve=>setTimeout(resolve,0));
const manifest={formatVersion:1 as const,appVersion:"0.1.0",schemaVersion:10,createdUnixSeconds:1,databaseSha256:"d".repeat(64),settingsSha256:"s".repeat(64),encrypted:false as const};
const source=()=>({exportPortableBackup:vi.fn().mockResolvedValue({manifest,warning:"unencrypted"}),inspectPortableBackup:vi.fn().mockResolvedValue({manifest,recordCounts:{experiences:3,resumes:2},appVersion:"0.1.0",schemaVersion:10,dryRun:true,pendingRestore:null,safetyBackup:null}),importPortableBackup:vi.fn().mockResolvedValue({manifest,recordCounts:{experiences:3,resumes:2},appVersion:"0.1.0",schemaVersion:10,dryRun:false,pendingRestore:"待恢复.db",safetyBackup:"安全备份.db",restartRequired:true})})as unknown as V2Actions;
const root=()=>{const value=document.createElement("div");value.innerHTML='<button data-export-portable>导出</button><button data-import-portable>导入</button>';return value};
beforeEach(()=>{vi.mocked(open).mockReset();vi.mocked(save).mockReset()});afterEach(()=>vi.unstubAllGlobals());
describe("W9 portable backup journey",()=>{
 it("uses exact strict command payloads",async()=>{const call=vi.fn().mockResolvedValue({success:true,data:{}}),client=new CareerCraftClient({call}as CommandTransport);await client.exportPortableBackup("C:\\中文\\履历.ccbackup",true);await client.inspectPortableBackup("C:\\中文\\履历.ccbackup");await client.importPortableBackup("C:\\中文\\履历.ccbackup",true);expect(call.mock.calls).toEqual([["export_portable_backup",{destinationPath:"C:\\中文\\履历.ccbackup",acknowledgeUnencrypted:true}],["inspect_portable_backup",{archivePath:"C:\\中文\\履历.ccbackup"}],["import_portable_backup",{archivePath:"C:\\中文\\履历.ccbackup",confirmed:true}]])});
 it("cancels native dialogs with zero backend calls",async()=>{vi.mocked(save).mockResolvedValue(null);vi.mocked(open).mockResolvedValue(null);const node=root(),api=source();bindPortable(node,api,new TaskStore());node.querySelector<HTMLButtonElement>("[data-export-portable]")!.click();node.querySelector<HTMLButtonElement>("[data-import-portable]")!.click();await tick();expect(api.exportPortableBackup).not.toHaveBeenCalled();expect(api.inspectPortableBackup).not.toHaveBeenCalled()});
 it("requires explicit unencrypted acknowledgement and never displays an API key",async()=>{vi.mocked(save).mockResolvedValue("C:\\用户\\履历.ccbackup");const node=root(),api=source();bindPortable(node,api,new TaskStore());node.querySelector<HTMLButtonElement>("[data-export-portable]")!.click();await tick();const confirm=node.querySelector<HTMLButtonElement>("[data-confirm-export]")!;expect(node.textContent).toContain("敏感履历数据未加密");expect(confirm.disabled).toBe(true);expect(node.textContent?.toLowerCase()).not.toContain("api key");const ack=node.querySelector<HTMLInputElement>("[data-export-ack]")!;ack.checked=true;ack.dispatchEvent(new Event("change"));confirm.click();await tick();expect(api.exportPortableBackup).toHaveBeenCalledWith("C:\\用户\\履历.ccbackup")});
 it("dry-runs before restore, shows hashes/schema/counts, and keeps preview on error",async()=>{vi.mocked(open).mockResolvedValue("C:\\用户\\职业数据.ccbackup");vi.stubGlobal("confirm",vi.fn().mockReturnValue(true));const node=root(),api=source(),tasks=new TaskStore();vi.mocked(api.importPortableBackup).mockRejectedValue({code:"VALIDATION",message:"数据包校验失败"});bindPortable(node,api,tasks);node.querySelector<HTMLButtonElement>("[data-import-portable]")!.click();await tick();expect(api.inspectPortableBackup).toHaveBeenCalledWith("C:\\用户\\职业数据.ccbackup");expect(node.textContent).toContain("未修改当前用户数据库");expect(node.textContent).toContain("临时候选文件已清理");expect(node.textContent).toContain("仅用于完整性校验");expect(node.textContent).toContain("不能证明数据包来源可信");expect(node.textContent).toContain("数据库结构版本");expect(node.textContent).toContain("experiences：3");expect(node.textContent).toContain("d".repeat(64));node.querySelector<HTMLButtonElement>("[data-confirm-import]")!.click();await tick();expect(api.importPortableBackup).toHaveBeenCalledWith("C:\\用户\\职业数据.ccbackup");expect(node.querySelector('[role="dialog"]')).not.toBeNull();expect(tasks.list().at(-1)).toMatchObject({phase:"failed",message:"数据包校验失败"})});
});
